# Generated by Django 2.1.5 on 2019-02-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_client', models.CharField(max_length=300)),
                ('job_description', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('completion_date', models.DateTimeField(verbose_name='completion date')),
                ('rejection_date', models.DateTimeField(verbose_name='rejection date')),
                ('is_flagged', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('rejection_text', models.TextField(max_length=500)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Designer')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Manufacturer'),
        ),
    ]
