# Generated by Django 2.1.5 on 2019-02-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='creation date'),
        ),
    ]
