# Generated by Django 2.1.5 on 2019-02-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190208_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rejection_text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
